import { defineConfig } from 'oxlint';

export default defineConfig({
  categories: {
    correctness: 'error',
    pedantic: 'warn',
    perf: 'warn',
    restriction: 'warn',
    style: 'warn',
    suspicious: 'warn',
  },
  env: {
    es2022: true,
    node: true,
  },
  overrides: [
    {
      files: ['**/scripts/*.ts'],
      rules: {
        'no-console': 'off',
      },
    },
  ],
  plugins: ['promise', 'typescript', 'unicorn'],
  rules: {
    'capitalized-comments': 'off',
    complexity: ['error', { max: 10 }],
    curly: 'off',
    'func-names': 'off',
    'func-style': ['warn', 'declaration'],
    'id-length': 'off',
    'import/extensions': 'error',
    'init-declarations': 'off',
    'max-lines': 'off',
    'max-lines-per-function': 'off',
    'max-statements': 'off',
    'no-console': 'warn',
    'no-implicit-globals': 'off',
    'no-inline-comments': 'off',
    'no-magic-numbers': 'off',
    'no-nested-ternary': 'off',
    'no-ternary': 'off',
    'no-undefined': 'off',
    'no-underscore-dangle': ['warn', { allow: ['_embedded'] }],
    'no-void': 'off',
    'one-var': 'off',
    'promise/prefer-await-to-then': 'warn',
    'require-await': 'off',
    'sort-imports': 'off',
    'typescript/explicit-function-return-type': 'off',
    'typescript/explicit-module-boundary-types': 'off',
    'typescript/no-non-null-assertion': 'off',
    'typescript/no-unsafe-type-assertion': 'off',
    'typescript/prefer-nullish-coalescing': 'off',
    'typescript/prefer-readonly-parameter-types': 'off',
    'typescript/strict-boolean-expressions': 'off',
    'unicorn/filename-case': 'off',
    'unicorn/max-nested-calls': 'off',
    'unicorn/prefer-global-this': 'off',
  },
});
